### ISSUE TITLE
Directory error in script

### ISSUE THREAD

**Issue by JuLeblanc** [embunnik/nanopore-amplicon-consensus#1]
Hello, 

I am a biologist trying to self-train in bioinformatics.

I have an issue with your code and after multiples tried I give up. 

This is the errors when I launch script_canu_consensus_1.sh: 
<img width="832" alt="MOBA_3" src="https://user-images.githubusercontent.com/89143771/129908087-61feb0c9-048c-4acc-a91b-456a2627bc32.PNG">

The script_canu_consensus_1.sh script:
<img width="938" alt="MOBA_2" src="https://user-images.githubusercontent.com/89143771/129908144-715fb1b4-de41-451e-8d33-facc49774484.PNG">

This is my repertories organizations : 
<img width="869" alt="MOBA_1" src="https://user-images.githubusercontent.com/89143771/129908146-e688521f-b520-4ee5-b896-5a9f42675a29.PNG">

I don't understand why he try to do this : 

cat: .//results/results/consensus_seqs: No such file or directory
cat: .//results/results/filtered_fastq: No such file or directory
cat: .//results/results/merged_fastq: No such file or directory

There is no directory called "result" in the "results" directory.  

I have a feeling that it doesn't work because of a small error but I can't find it. 

If you can help a noob. 

Thanks a lot !

**Comment by embunnik** [comment]
Hi!

I think more than one thing is going wrong, but hopefully can be fixed easily:

- The directory provided in the command should be given as the name only, without the preceding '/'
- This directory needs to contain the fastq files that you want to process (I don't see any fastq files when you show the contents of the 'results' directory in the third image)
- canu needs to be in your PATH (first image, line 10 says 'canu: command not found')

Hope this helps!

**Comment by JuLeblanc** [comment]
Hello,

Thank you for your quick answer! 
Thanks to your debugging, your code runs (almost) perfectly.

In fact, there is still a problem, I have no files in the "consensus_seqs" directories. 
All others directories content files !! 

**Some details about what I have and what I want** (actually, what I would like to have):

**I have** 9 barecode directories, all directories are from the **same sequencing run** where I have mixed 9 synthetic DNA sequences (previously barecoded). 
Barecode 1, Barecode 2, Barecode 3 = 3 differents synthetic DNA sequencesof 500 nt length.
Barecode 4, Barecode 5, Barecode 6, Barecode 7, Barecode 8, Barecode 9 = 6 differents synthetic DNA sequences of 1000 nt length.

**I just wish** a consensus sequence for each barcode. The goal is just to check if I can find the synthetic DNA sequences I designed after sequencing them.

I put you the output file from consensus_fastq repertories of barcode01 and barcode09 (there are differents):
[barcode01_canu.out.txt](https://github.com/embunnik/nanopore-amplicon-consensus/files/7012789/barcode01_canu.out.txt)
[barcode09_canu.out.txt](https://github.com/embunnik/nanopore-amplicon-consensus/files/7012790/barcode09_canu.out.txt)
) .


Thank you again,
Sorry again for the inconvenience.

**Comment by embunnik** [comment]
The wrapper script seems to be working fine now, but canu does not give you the desired output. For barcode01, canu encountered an error and exited. For barcode09, canu ran without errors but did not produce a consensus sequence. I have seen this a few times - I assume this happens when there is not enough similarity among the sequence reads to create a consensus. I would advise you to contact the developers of canu to see if they can provide more insight. 

Good luck!

**Comment by JuLeblanc** [comment]
Hello,

Ok, thanks again!

I will ask Canu and maybe some bioinformaticians from another team of my group.

Thanks for your work and for making it accesible to the community :-)
